# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dg-web-prod-neu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com/isahurtado97/ghost/
        username: ${{ secrets.AzureAppService_ContainerUsername_97fc1a7f639d452a9d353b47d35ce1be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_092a6297a6864a36997363edebd85d84 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com/isahurtado97/ghost/${{ secrets.AzureAppService_ContainerUsername_97fc1a7f639d452a9d353b47d35ce1be }}/ghost:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dg-web-prod-neu'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_357b34e8f4b64a5781bb48416639bde1 }}
        images: 'github.com/isahurtado97/ghost/${{ secrets.AzureAppService_ContainerUsername_97fc1a7f639d452a9d353b47d35ce1be }}/ghost:${{ github.sha }}'